object DependencyVersions {

  val circe                  = "0.14.6"
  val `circe-generic-extras` = "0.14.3"
  val `circe-yaml`           = "0.14.2"
  val `cats-effect`          = "3.5.2"
  val fs2                    = "3.9.2"
  val monocle                = "3.2.0"
  val http4s                 = "0.23.23"
  val `scala-uri`            = "4.0.3"
  val decline                = "2.4.1"
  val log4cats               = "2.6.0"
  val `scalajs-dom`          = "2.0.0"
  val `cats-retry`           = "3.1.0"
  val woof                   = "0.2.1"
  val keypool                = "0.4.8"
  val playwright             = "1.38.0"
  val redis4cats             = "1.5.0"
  val `typesafe-config`      = "1.4.2"
  val `circe-config`         = "0.10.0"
  val logback                = "1.2.11"
  val slf4j                  = "1.7.36"
  val ip4s                   = "3.3.0"
  val scalatest              = "3.2.17"
}
